name: Experimantal

on:
  push:
    branches: [ experimental/* ]

jobs:
  get-pkg-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract package version
        shell: bash
        run: |
          ROOT_PATH="${1-.}"
          PKG_JSON_PATH="${ROOT_PATH}/package.json"
          PKG_VERSION=$(jq -r '.version' < "${PKG_JSON_PATH}")
          echo "PKG_VERSION=${PKG_VERSION}" >> $GITHUB_ENV

      - name: Print package version
        shell: bash
        run: echo "Package version is ${{ github.env.PKG_VERSION }}"
