name: Experimantal

on:
  push:
    branches: [ experimental/* ]

jobs:
  get-pkg-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get package version
        id: pkg-version
        shell: bash
        run: |
          ROOT_PATH="${1-.}"
          echo "Using root path: $ROOT_PATH"

          PKG_JSON_PATH="${ROOT_PATH}/package.json"
          echo "Reading package.json from $PKG_JSON_PATH"

          PKG_VERSION=$(jq -r '.version' < "${PKG_JSON_PATH}")
          echo "Package version is $PKG_VERSION"

          echo "PKG_VERSION=${PKG_VERSION}" >> $GITHUB_OUTPUT
          echo "Output: \"$GITHUB_OUTPUT\""

      - name: Print package version
        if: false
        run: echo "Package version is ${{ steps.pkg-version.outputs.version }}"
