name: Release Drafter

on:
  push:
    branches: ['main']

  # pull_request event is required for autolabeler
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read

concurrency:
  group: release-drafter
  cancel-in-progress: true

jobs:
  update_release_draft:
    permissions:
      # write permission is required to create a github release
      contents: write

    runs-on: ubuntu-latest

    steps:
      # Drafts your next Release notes as Pull Requests are merged into "main"
      - uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter-config.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
